name: First Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  inspects:
    runs-on: ubuntu-latest

    steps:
      - name: Load Code
        uses: actions/checkout@v4

      - name: Show Repo Files
        run: ls -la
      - name: Current folder
        run: pwd

      - name: Last 3 commits
        run: git log -3 --oneline
